[package]
name = "sveio"
version = "0.1.0"
edition = "2021"

[dependencies]
socketioxide = {version = "0.13.1", features=["extensions", "state"]}
tokio = {version = "1.37.0", features=["full"]}
tower-http = {version = "0.5.2", features=["cors", "fs"]}
serde = {version = "1.0", features=["derive"]}
rand = {version = "0.8.5", features=["std_rng"]}
axum = "0.7.5"
serde_json = "1.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tower = "0.4.13"
dotenvy = "0.15.7"
geoutils = "0.5.1"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
panic = "abort"
strip = "symbols"
